insert into public.brands (slug, name)
values
  ('roborock', 'Roborock'),
  ('dreame', 'Dreame'),
  ('xiaomi', 'Xiaomi');

insert into public.products (
  slug, brand_id, name, asin, gtin, pa_suction, navigation, mop_type, dock,
  pet_hair, carpets, small_flat, height_mm, for_whom, not_for_whom, summary, status
)
values
  (
    'roborock-qrevo-s5v',
    (select id from public.brands where slug = 'roborock'),
    'Roborock Qrevo S5V',
    'B0DT13JGY2',
    '00810125544057',
    12000,
    'LiDAR PreciSense, hasta cuatro mapas, y luz estructurada para los obstáculos',
    'Dos mopas giratorias con brazo al borde, elevables 10 mm',
    'wash_dry',
    true,
    true,
    false,
    97,
    'Para un piso con pelo y alfombras de pelo bajo, cuando quieres dejar de vaciar el depósito a mano. La base vacía, lava y seca. El cuerpo mide 97 mm: bajo un sofá más bajo no entra.',
    'No encaja si no cabe una estación grande. Si el hueco es el límite, mira el Dreame L10s Pro Gen 3, que solo carga y está marcado como piso pequeño.',
    'Qrevo con 12.000 Pa, mapa LiDAR y base que vacía, lava y seca.',
    'published'
  ),
  (
    'roborock-qrevo-s-pro',
    (select id from public.brands where slug = 'roborock'),
    'Roborock Qrevo S Pro',
    'B0GHN3V6BP',
    '00810125545085',
    18500,
    'Detección de obstáculos. La ficha no nombra el sistema de mapa',
    'Dos mopas con caudal de agua ajustable',
    'wash_dry',
    true,
    false,
    false,
    97,
    'Para una casa con mascotas en la que quieres que la base vacíe, lave y seque. El cuerpo mide 97 mm.',
    'No encaja si la estación no cabe o si el hueco bajo los muebles es menor de 97 mm. Para pasar más bajo, el Qrevo EdgeT mide 80 mm y también está marcado para pelo.',
    'Qrevo S Pro con 18.500 Pa y base que vacía, lava a 75 °C y seca a 45 °C.',
    'published'
  ),
  (
    'roborock-qv-35a',
    (select id from public.brands where slug = 'roborock'),
    'Roborock QV 35A',
    'B0DSLBN5FS',
    '00810125543609',
    8000,
    'Navegación y mapeo, con Reactive Tech para esquivar cables, zapatos y muebles',
    'Dos mopas giratorias a 200 rpm, elevables 10 mm',
    'wash_dry',
    false,
    false,
    false,
    null,
    'Para quien quiere una estación que vacía, rellena, lava y seca y se queda en 8.000 Pa. No está marcado para pelo ni para alfombras. La altura del cuerpo no consta.',
    'No encaja si hay mascota o si buscas la succión de un Qrevo de 18.500 Pa. Si hay pelo, mira el Roborock Qrevo S5V.',
    'QV 35A con 8.000 Pa y base que vacía, rellena, lava y seca.',
    'published'
  ),
  (
    'roborock-qrevo-edget',
    (select id from public.brands where slug = 'roborock'),
    'Roborock Qrevo EdgeT',
    'B0GSZ6BPW9',
    '00810125545283',
    18500,
    'Reactive AI con luz estructurada y cámara RGB',
    'Dos mopas giratorias elevables 10 mm y mopa de borde FlexiArm',
    'wash_dry',
    true,
    false,
    false,
    80,
    'Para un piso con muebles bajos y pelo de mascota, si cabe una base grande. A 80 mm entra donde un cuerpo de 97 mm no. La estación vacía, lava y seca.',
    'No encaja si la estación no cabe. En ese caso mira el Dreame L10s Pro Gen 3, de solo carga. Esta ficha no está marcada para alfombras.',
    'Qrevo EdgeT con 18.500 Pa, cuerpo de 7,98 cm y base que vacía, lava y seca.',
    'published'
  ),
  (
    'roborock-qrevo-2-pro',
    (select id from public.brands where slug = 'roborock'),
    'Roborock Qrevo 2 Pro',
    'B0GZZ96X7N',
    '00810125545399',
    25000,
    'Navegación SLAM y evitación Reactive Tech',
    'Mopa FlexiArm que se retira o se eleva hasta 15 mm en la alfombra',
    'wash_dry',
    false,
    true,
    false,
    97,
    'Para quien quiere 25.000 Pa y una base que vacía, lava y seca, sobre todo con alfombra: sube la potencia en el tejido y la mopa puede elevarse hasta 15 mm. El cuerpo mide 97 mm.',
    'No encaja bajo muebles de menos de 97 mm ni si buscas una ficha marcada para pelo. Si hay mascota y quieres pasar más bajo, mira el Qrevo EdgeT.',
    'Qrevo 2 Pro con 25.000 Pa, sube la potencia en la alfombra y la base lo hace casi todo.',
    'published'
  ),
  (
    'roborock-qrevo-5ae',
    (select id from public.brands where slug = 'roborock'),
    'Roborock Qrevo 5AE',
    'B0DZ26MJMJ',
    null,
    12000,
    'Luz estructurada para esquivar obstáculos. La ficha no nombra el sistema de mapa',
    'Dos mopas giratorias elevables 10 mm, con brazo extensible',
    'wash_dry',
    false,
    false,
    false,
    97,
    'Para quien quiere el Qrevo 5AE con base que vacía, lava, seca y rellena el agua, y acepta un vendedor que no es la tienda oficial. El cuerpo mide 97 mm. No está marcado para pelo ni para alfombras.',
    'No encaja si necesitas la ficha en español de la tienda oficial, o si hay pelo. Para pelo y alfombra de pelo bajo, mira el Qrevo S5V.',
    'Qrevo 5AE con 12.000 Pa y base que vacía, lava, seca y rellena el agua.',
    'published'
  ),
  (
    'dreame-l40-ultra-ae',
    (select id from public.brands where slug = 'dreame'),
    'Dreame L40 Ultra AE',
    'B0F53MJY8T',
    null,
    19000,
    'Elusión 3DAdapt. La ficha no llama LiDAR al mapa',
    'Mopa extensible, elevable 10,5 mm. Puede alternar cepillo de goma y TriCut',
    'wash_dry',
    true,
    true,
    false,
    null,
    'Para un piso grande con alfombras y mascotas, si cabe la PowerDock. Esa base vacía, lava a 75 °C y seca con aire caliente. La altura del robot no consta en esta ficha.',
    'No encaja en un piso pequeño. Si no cabe la estación, mira el Dreame L10s Pro Gen 3, de solo carga.',
    'L40 Ultra AE con 19.000 Pa y PowerDock que vacía, lava a 75 °C y seca con aire caliente.',
    'published'
  ),
  (
    'dreame-l40-ultra-a',
    (select id from public.brands where slug = 'dreame'),
    'Dreame L40 Ultra A',
    'B0GQBX475S',
    null,
    24000,
    'Mapeo con guía láser',
    'Mopas extensibles unos 4 cm, elevables 10,5 mm',
    'wash_dry',
    false,
    false,
    false,
    null,
    'Para quien quiere un L40 de 24.000 Pa con base que vacía, lava y seca al aire, y no necesita el secado con aire caliente del AE. No está marcado para pelo ni para alfombras. La altura del robot no consta.',
    'No encaja si buscas secado con aire caliente o si hay mascota. Para pelo, alfombra y aire caliente, mira el L40 Ultra AE.',
    'L40 Ultra A con 24.000 Pa y base que vacía, lava y seca al aire.',
    'published'
  ),
  (
    'dreame-l10s-ultra-gen-3',
    (select id from public.brands where slug = 'dreame'),
    'Dreame L10s Ultra Gen 3',
    'B0FN8FR84Q',
    null,
    25000,
    'Láser de una línea, navegación inteligente y elusión 3DAdapt',
    'Cepillo lateral y mopa extensibles, mopa elevable 10,5 mm',
    'wash_dry',
    true,
    true,
    false,
    null,
    'Para alfombras y pelo, con 25.000 Pa y una estación que vacía, lava, seca y rellena agua y detergente. La altura del robot no consta; la estación es grande.',
    'No encaja en un piso pequeño. Si el hueco manda, mira el L10s Pro Gen 3, que solo carga y mide 97 mm. Si te basta con 10.000 Pa, el Gen 2 también tiene estación y está marcado para pelo.',
    'L10s Ultra Gen 3 con 25.000 Pa y base que vacía, lava, seca y rellena agua y detergente.',
    'published'
  ),
  (
    'dreame-l10s-ultra-gen-2',
    (select id from public.brands where slug = 'dreame'),
    'Dreame L10s Ultra Gen 2',
    'B0DCVYS9FQ',
    null,
    10000,
    'Láser de una línea y mapa de varias plantas',
    'Mopa extensible RoboSwing',
    'wash_dry',
    true,
    true,
    false,
    97,
    'Para quien quiere una estación que vacía, lava y seca, con mascota, en 10.000 Pa. El cuerpo mide 97 mm.',
    'No encaja si necesitas la succión del Gen 3 o si la estación no cabe. Si no cabe, mira el L10s Pro Gen 3.',
    'L10s Ultra Gen 2 con 10.000 Pa, modo de mascotas y estación que lava y seca.',
    'published'
  ),
  (
    'dreame-l10s-pro-gen-3',
    (select id from public.brands where slug = 'dreame'),
    'Dreame L10s Pro Gen 3',
    'B0FJFK8H15',
    null,
    13000,
    'Smart Pathfinder. La ficha no lo llama LiDAR',
    'Dos mopas DuoScrub, RoboSwing y elevación de 7 mm',
    'none',
    false,
    true,
    true,
    97,
    'Para un piso pequeño o mediano que quiere aspirar y fregar sin dejar el recibidor a una torre. La base solo carga: el depósito y la mopa los atiendes tú. El cuerpo mide 97 mm y la base de carga mide 9,3 cm de alta.',
    'No encaja si quieres que la base vacíe, lave o seque la mopa. Si cabe la estación y hay pelo, mira el L10s Ultra Gen 2.',
    'L10s Pro Gen 3 con 13.000 Pa, fregado DuoScrub y base de carga.',
    'published'
  ),
  (
    'xiaomi-robot-vacuum-x20-plus',
    (select id from public.brands where slug = 'xiaomi'),
    'Xiaomi Robot Vacuum X20+',
    'B0CTCXKL52',
    '06941812768556',
    6000,
    'Escaneo de 360° (S-Cross) y varias plantas',
    'Dos mopas giratorias que se levantan en la alfombra',
    'wash_dry',
    false,
    true,
    false,
    97,
    'Para una primera estación de esta gama: vacía, lava y seca, con 6.000 Pa y alfombras en las que la mopa se levanta. El cuerpo mide 97 mm. No está marcado para pelo.',
    'No encaja si necesitas más succión o si hay mascota. El X20 Max sube a 8.000 Pa y alarga el brazo de la mopa. También mide 97 mm.',
    'X20+ con 6.000 Pa y estación que vacía, lava y seca las mopas.',
    'published'
  ),
  (
    'xiaomi-robot-vacuum-x20-max',
    (select id from public.brands where slug = 'xiaomi'),
    'Xiaomi Robot Vacuum X20 Max',
    'B0DFHW2JTT',
    null,
    8000,
    'LDS, luz estructurada y láser de bordes',
    'Mopa con brazo de hasta 4 cm, que se levanta al detectar alfombra',
    'wash_dry',
    false,
    true,
    false,
    97,
    'Para quien el X20+ se queda en 6.000 Pa y quiere 8.000 Pa más el brazo de la mopa, que sale hasta 4 cm y se levanta en la alfombra. La estación lava en caliente y seca. El cuerpo mide 97 mm. No está marcado para pelo.',
    'No encaja si buscas el X20+ más sencillo, ni si hay mascota. Para pelo en esta gama, mira el Qrevo S5V.',
    'X20 Max con 8.000 Pa y estación que lava las mopas en caliente y las seca.',
    'published'
  ),
  (
    'xiaomi-robot-vacuum-x20-pro',
    (select id from public.brands where slug = 'xiaomi'),
    'Xiaomi Robot Vacuum X20 Pro',
    'B0DFJGKW2L',
    null,
    7000,
    'Navegación LDS',
    'Fregado; la estación lava las mopas en caliente y las seca con aire caliente',
    'wash_dry',
    false,
    false,
    false,
    97,
    'Para quien quiere la estación con agua caliente y se queda en 7.000 Pa, entre el X20+ y el Max. El cuerpo mide 97 mm. No está marcado para pelo ni para alfombras.',
    'No encaja si quieres el brazo extensible del X20 Max o si hay alfombra que haya que tratar. El Max sí está marcado para alfombras.',
    'X20 Pro con 7.000 Pa y estación que vacía, lava en caliente y seca.',
    'published'
  );

insert into public.product_variants (product_id, color, asin)
values
  ((select id from public.products where slug = 'roborock-qrevo-s5v'), 'Negro', 'B0DT13JGY2'),
  ((select id from public.products where slug = 'roborock-qrevo-s5v'), 'Blanco', 'B0DSMQRZFY'),
  ((select id from public.products where slug = 'roborock-qrevo-s-pro'), 'Negro', 'B0GHN3V6BP'),
  ((select id from public.products where slug = 'roborock-qv-35a'), 'Negro', 'B0DSLBN5FS'),
  ((select id from public.products where slug = 'roborock-qrevo-edget'), 'Blanco', 'B0GSZ6BPW9'),
  ((select id from public.products where slug = 'roborock-qrevo-2-pro'), 'Blanco', 'B0GZZ96X7N'),
  ((select id from public.products where slug = 'roborock-qrevo-5ae'), 'Negro', 'B0DZ26MJMJ'),
  ((select id from public.products where slug = 'dreame-l40-ultra-a'), 'Blanco', 'B0GQBX475S'),
  ((select id from public.products where slug = 'dreame-l10s-pro-gen-3'), 'Blanco', 'B0FJFK8H15'),
  ((select id from public.products where slug = 'dreame-l10s-pro-gen-3'), 'Negro', 'B0CW1S1H5X'),
  ((select id from public.products where slug = 'xiaomi-robot-vacuum-x20-max'), 'Negro', 'B0DFHW2JTT'),
  ((select id from public.products where slug = 'xiaomi-robot-vacuum-x20-pro'), 'Blanco', 'B0DFJGKW2L');
