insert into public.brands (slug, name)
values
  ('roborock', 'Roborock'),
  ('dreame', 'Dreame'),
  ('xiaomi', 'Xiaomi');

insert into public.products (
  slug, brand_id, name, asin, gtin, pa_suction, navigation, mop_type, dock,
  pet_hair, carpets, small_flat, height_mm, for_whom, not_for_whom, summary, status
)
values
  (
    'roborock-qrevo-s5v',
    (select id from public.brands where slug = 'roborock'),
    'Roborock Qrevo S5V',
    'B0DT13JGY2',
    '00810125544057',
    12000,
    'LiDAR PreciSense, hasta cuatro mapas, y luz estructurada para los obstáculos',
    'Dos mopas giratorias con brazo al borde, elevables 10 mm',
    'wash_dry',
    true,
    true,
    false,
    null,
    'Para un piso con pelo y alfombras de pelo bajo, cuando interesa dejar de vaciar el depósito a mano.',
    'No encaja si no cabe una base que vacía, lava y seca.',
    'Qrevo con 12.000 Pa, mapa LiDAR y base que vacía, lava y seca.',
    'published'
  ),
  (
    'roborock-qrevo-s-pro',
    (select id from public.brands where slug = 'roborock'),
    'Roborock Qrevo S Pro',
    'B0GHN3V6BP',
    '00810125545085',
    18500,
    'Detección de obstáculos. La ficha no nombra el sistema de mapa',
    'Dos mopas con caudal de agua ajustable',
    'wash_dry',
    true,
    false,
    false,
    97,
    'Para una casa con mascotas que quiere la base que vacía, lava y seca.',
    'No encaja si no cabe una base grande. La ficha da 9,65 cm de altura para pasar bajo muebles.',
    'Qrevo S Pro con 18.500 Pa y base que vacía, lava a 75 °C y seca a 45 °C.',
    'published'
  ),
  (
    'roborock-qv-35a',
    (select id from public.brands where slug = 'roborock'),
    'Roborock QV 35A',
    'B0DSLBN5FS',
    '00810125543609',
    8000,
    'Navegación y mapeo, con Reactive Tech para esquivar cables, zapatos y muebles',
    'Dos mopas giratorias a 200 rpm, elevables 10 mm',
    'wash_dry',
    false,
    false,
    false,
    null,
    'Para quien quiere estación todo en uno y se queda en la parte baja de esta gama.',
    'No encaja si buscas la succión de los Qrevo de 18.500 Pa.',
    'QV 35A con 8.000 Pa y base que vacía, rellena, lava y seca.',
    'published'
  ),
  (
    'roborock-qrevo-edget',
    (select id from public.brands where slug = 'roborock'),
    'Roborock Qrevo EdgeT',
    'B0GSZ6BPW9',
    '00810125545283',
    18500,
    'Reactive AI con luz estructurada y cámara RGB',
    'Dos mopas giratorias elevables 10 mm y mopa de borde FlexiArm',
    'wash_dry',
    true,
    false,
    false,
    80,
    'Para un piso con muebles bajos y pelo de mascota, si cabe una base grande.',
    'No encaja si no cabe la base. La ficha da 7,98 cm de altura.',
    'Qrevo EdgeT con 18.500 Pa, cuerpo de 7,98 cm y base que vacía, lava y seca.',
    'published'
  ),
  (
    'roborock-qrevo-2-pro',
    (select id from public.brands where slug = 'roborock'),
    'Roborock Qrevo 2 Pro',
    'B0GZZ96X7N',
    '00810125545399',
    25000,
    'Navegación SLAM y evitación Reactive Tech',
    'Mopa FlexiArm que se retira o se eleva hasta 15 mm en la alfombra',
    'wash_dry',
    false,
    true,
    false,
    97,
    'Para quien quiere mucha succión y una base que vacía, lava y seca.',
    'No encaja bajo muebles muy bajos: la ficha da 9,65 cm.',
    'Qrevo 2 Pro con 25.000 Pa, sube la potencia en la alfombra y la base lo hace casi todo.',
    'published'
  ),
  (
    'roborock-qrevo-5ae',
    (select id from public.brands where slug = 'roborock'),
    'Roborock Qrevo 5AE',
    'B0DZ26MJMJ',
    null,
    12000,
    'Luz estructurada para esquivar obstáculos. La ficha no nombra el sistema de mapa',
    'Dos mopas giratorias elevables 10 mm, con brazo extensible',
    'wash_dry',
    false,
    false,
    false,
    null,
    'Para quien quiere el Qrevo 5AE con base que vacía, lava y seca, y acepta un vendedor que no es la tienda oficial.',
    'No encaja si necesitas una ficha con el título en español de la tienda oficial.',
    'Qrevo 5AE con 12.000 Pa y base que vacía, lava, seca y rellena el agua.',
    'published'
  ),
  (
    'dreame-l40-ultra-ae',
    (select id from public.brands where slug = 'dreame'),
    'Dreame L40 Ultra AE',
    'B0F53MJY8T',
    null,
    19000,
    'Elusión 3DAdapt. La ficha no llama LiDAR al mapa',
    'Mopa extensible, elevable 10,5 mm. Puede alternar cepillo de goma y TriCut',
    'wash_dry',
    true,
    true,
    false,
    null,
    'Para un piso grande con alfombras y mascotas.',
    'No encaja en un piso pequeño.',
    'L40 Ultra AE con 19.000 Pa y PowerDock que vacía, lava a 75 °C y seca con aire caliente.',
    'published'
  ),
  (
    'dreame-l40-ultra-a',
    (select id from public.brands where slug = 'dreame'),
    'Dreame L40 Ultra A',
    'B0GQBX475S',
    null,
    24000,
    'Mapeo con guía láser',
    'Mopas extensibles unos 4 cm, elevables 10,5 mm',
    'wash_dry',
    false,
    false,
    false,
    null,
    'Para quien quiere un L40 con base y no necesita el AE.',
    'No encaja si buscas secado con aire caliente: la ficha habla de secado al aire.',
    'L40 Ultra A con 24.000 Pa y base que vacía, lava y seca al aire.',
    'published'
  ),
  (
    'dreame-l10s-ultra-gen-3',
    (select id from public.brands where slug = 'dreame'),
    'Dreame L10s Ultra Gen 3',
    'B0FN8FR84Q',
    null,
    25000,
    'Láser de una línea, navegación inteligente y elusión 3DAdapt',
    'Cepillo lateral y mopa extensibles, mopa elevable 10,5 mm',
    'wash_dry',
    true,
    true,
    false,
    null,
    'Para alfombras y pelo de mascota, con estación que vacía y seca.',
    'No encaja en un piso pequeño: la estación es grande.',
    'L10s Ultra Gen 3 con 25.000 Pa y base que vacía, lava, seca y rellena agua y detergente.',
    'published'
  ),
  (
    'dreame-l10s-ultra-gen-2',
    (select id from public.brands where slug = 'dreame'),
    'Dreame L10s Ultra Gen 2',
    'B0DCVYS9FQ',
    null,
    10000,
    'Láser de una línea y mapa de varias plantas',
    'Mopa extensible RoboSwing',
    'wash_dry',
    true,
    true,
    false,
    null,
    'Para quien quiere estación automática en la parte baja de esta gama y tiene mascota.',
    'No encaja si necesitas la succión del Gen 3.',
    'L10s Ultra Gen 2 con 10.000 Pa, modo de mascotas y estación que lava y seca.',
    'published'
  ),
  (
    'dreame-l10s-pro-gen-3',
    (select id from public.brands where slug = 'dreame'),
    'Dreame L10s Pro Gen 3',
    'B0FJFK8H15',
    null,
    13000,
    'Smart Pathfinder. La ficha no lo llama LiDAR',
    'Dos mopas DuoScrub, RoboSwing y elevación de 7 mm',
    'none',
    false,
    true,
    true,
    null,
    'Para un piso pequeño o mediano que quiere fregado y no una base que ocupe el baño.',
    'No encaja si quieres que la base vacíe, lave o seque la mopa. Solo vuelve a cargarse.',
    'L10s Pro Gen 3 con 13.000 Pa, fregado DuoScrub y base de carga.',
    'published'
  ),
  (
    'xiaomi-robot-vacuum-x20-plus',
    (select id from public.brands where slug = 'xiaomi'),
    'Xiaomi Robot Vacuum X20+',
    'B0CTCXKL52',
    '06941812768556',
    6000,
    'Escaneo de 360° (S-Cross) y varias plantas',
    'Dos mopas giratorias que se levantan en la alfombra',
    'wash_dry',
    false,
    true,
    false,
    null,
    'Para una primera compra de la gama, con estación que vacía, lava y seca.',
    'No encaja si necesitas más de 6.000 Pa.',
    'X20+ con 6.000 Pa y estación que vacía, lava y seca las mopas.',
    'published'
  ),
  (
    'xiaomi-robot-vacuum-x20-max',
    (select id from public.brands where slug = 'xiaomi'),
    'Xiaomi Robot Vacuum X20 Max',
    'B0DFHW2JTT',
    null,
    8000,
    'LDS, luz estructurada y láser de bordes',
    'Mopa con brazo de hasta 4 cm, que se levanta al detectar alfombra',
    'wash_dry',
    false,
    true,
    false,
    null,
    'Para quien el X20+ se queda corto de succión y quiere el brazo que llega al borde.',
    'No encaja si buscas el X20+ de 6.000 Pa.',
    'X20 Max con 8.000 Pa y estación que lava las mopas en caliente y las seca.',
    'published'
  ),
  (
    'xiaomi-robot-vacuum-x20-pro',
    (select id from public.brands where slug = 'xiaomi'),
    'Xiaomi Robot Vacuum X20 Pro',
    'B0DFJGKW2L',
    null,
    7000,
    'Navegación LDS',
    'Fregado; la estación lava las mopas en caliente y las seca con aire caliente',
    'wash_dry',
    false,
    false,
    false,
    null,
    'Para quien quiere estación con agua caliente y se queda entre el X20+ y el Max.',
    'No encaja si quieres el brazo extensible del X20 Max.',
    'X20 Pro con 7.000 Pa y estación que vacía, lava en caliente y seca.',
    'published'
  );

insert into public.product_variants (product_id, color, asin)
values
  ((select id from public.products where slug = 'roborock-qrevo-s5v'), 'Negro', 'B0DT13JGY2'),
  ((select id from public.products where slug = 'roborock-qrevo-s5v'), 'Blanco', 'B0DSMQRZFY'),
  ((select id from public.products where slug = 'roborock-qrevo-s-pro'), 'Negro', 'B0GHN3V6BP'),
  ((select id from public.products where slug = 'roborock-qv-35a'), 'Negro', 'B0DSLBN5FS'),
  ((select id from public.products where slug = 'roborock-qrevo-edget'), 'Blanco', 'B0GSZ6BPW9'),
  ((select id from public.products where slug = 'roborock-qrevo-2-pro'), 'Blanco', 'B0GZZ96X7N'),
  ((select id from public.products where slug = 'roborock-qrevo-5ae'), 'Negro', 'B0DZ26MJMJ'),
  ((select id from public.products where slug = 'dreame-l40-ultra-a'), 'Blanco', 'B0GQBX475S'),
  ((select id from public.products where slug = 'dreame-l10s-pro-gen-3'), 'Blanco', 'B0FJFK8H15'),
  ((select id from public.products where slug = 'dreame-l10s-pro-gen-3'), 'Negro', 'B0CW1S1H5X'),
  ((select id from public.products where slug = 'xiaomi-robot-vacuum-x20-max'), 'Negro', 'B0DFHW2JTT'),
  ((select id from public.products where slug = 'xiaomi-robot-vacuum-x20-pro'), 'Blanco', 'B0DFJGKW2L');
