update public.products set navigation = 'Detección de obstáculos' where slug = 'roborock-qrevo-s-pro';
update public.products set navigation = 'Luz estructurada para esquivar obstáculos' where slug = 'roborock-qrevo-5ae';
update public.products set navigation = 'Elusión 3DAdapt' where slug = 'dreame-l40-ultra-ae';
update public.products set navigation = 'Smart Pathfinder' where slug = 'dreame-l10s-pro-gen-3';

update public.products set not_for_whom = 'No encaja si no cabe una estación grande. Si el hueco es el límite, mira el Dreame L10s Pro Gen 3, que solo carga y cabe en un piso pequeño.' where slug = 'roborock-qrevo-s5v';
update public.products set not_for_whom = 'No encaja si la estación no cabe o si el hueco bajo los muebles es menor de 97 mm. Para pasar más bajo, el Qrevo EdgeT mide 80 mm y también vale si hay pelo.' where slug = 'roborock-qrevo-s-pro';
update public.products set for_whom = 'Para quien quiere una estación que vacía, rellena, lava y seca y se queda en 8.000 Pa. No es la elección si hay pelo o alfombras.' where slug = 'roborock-qv-35a';
update public.products set not_for_whom = 'No encaja si la estación no cabe. En ese caso mira el Dreame L10s Pro Gen 3, de solo carga. No es la opción si la alfombra es lo que más te importa.' where slug = 'roborock-qrevo-edget';
update public.products set for_whom = 'Para quien quiere el Qrevo 5AE con base que vacía, lava, seca y rellena el agua. El cuerpo mide 97 mm.', not_for_whom = 'No encaja si hay pelo o alfombras. Para pelo y alfombra de pelo bajo, mira el Qrevo S5V.' where slug = 'roborock-qrevo-5ae';
update public.products set for_whom = 'Para un piso grande con alfombras y mascotas, si cabe la PowerDock. Esa base vacía, lava a 75 °C y seca con aire caliente.' where slug = 'dreame-l40-ultra-ae';
update public.products set for_whom = 'Para quien quiere un L40 de 24.000 Pa con base que vacía, lava y seca al aire, y no necesita el secado con aire caliente del AE.' where slug = 'dreame-l40-ultra-a';
update public.products set for_whom = 'Para alfombras y pelo, con 25.000 Pa y una estación que vacía, lava, seca y rellena agua y detergente. La estación es grande.', not_for_whom = 'No encaja en un piso pequeño. Si el hueco manda, mira el L10s Pro Gen 3, que solo carga y mide 97 mm. Si te basta con 10.000 Pa, el Gen 2 también tiene estación y vale si hay pelo.' where slug = 'dreame-l10s-ultra-gen-3';
update public.products set for_whom = 'Para una primera estación de esta gama: vacía, lava y seca, con 6.000 Pa y alfombras en las que la mopa se levanta. El cuerpo mide 97 mm.' where slug = 'xiaomi-robot-vacuum-x20-plus';
update public.products set for_whom = 'Para quien el X20+ se queda en 6.000 Pa y quiere 8.000 Pa más el brazo de la mopa, que sale hasta 4 cm y se levanta en la alfombra. La estación lava en caliente y seca. El cuerpo mide 97 mm.' where slug = 'xiaomi-robot-vacuum-x20-max';
update public.products set for_whom = 'Para quien quiere la estación con agua caliente y se queda en 7.000 Pa, entre el X20+ y el Max. El cuerpo mide 97 mm.', not_for_whom = 'No encaja si quieres el brazo extensible del X20 Max o si hay alfombra que haya que tratar. El Max sí trata alfombras.' where slug = 'xiaomi-robot-vacuum-x20-pro';
